### ISSUE TITLE
Implement missing `__reduce__` and `__reduce_ex__` for several types

### ISSUE THREAD

**Issue by Snowapril** [RustPython/RustPython#3611]
## Feature
Many existing test cases check that `pickle.dumps` and `pickle.loads` of a given type return the exact same value. Almost failed pickle test in RustPython, lack `__reduce__` method.

- [x] `arrayiterator.__reduce__` (test_array::test_iterator_pickle) — #3868
- [x] `filter.__reduce__` (test_builtin::test_filter_pickle) — #3732
- [x] `map.__reduce__` (test_builtin::test_map_pickle) — #3734
- [x] `ImportError.__reduce__` (test_exceptions::test_copy_pickle) — #4973
- [x] `OSError.__reduce__` — #4191 
- [x] `BaseException.__reduce__` — #3665
- [x] `method.__reduce__` — #4237 
- [ ] `groupby.__reduce__`
- [ ] `_grouper.__reduce__`
- [ ] `tee.__reduce__`
- [ ] `cycle.__reduce__`
- [x] `dropwhile.__reduce__` — #4201 
- [x] `takewhile.__reduce__` — #4190
- [x] `islice.__reduce__` — #4390
- [x] `starmap.__reduce__` — #3988 
- [x] `chain.__reduce__` — #4232
- [x] `product.__reduce__` #5089 
- [x] `combinations.__reduce__` — #3931, #4272
- [ ] `combinations_with_replacement.__reduce__`
- [x] `permutations.__reduce__` #5029
- [x] `accumulate.__reduce__` #4434
- [x] `compress.__reduce__` — #3791
- [x] `filterfalse.__reduce__` — #3745
- [x] `count.__reduce__` — #3737
- [x] `zip_longest.__reduce__` #4235
- [x] `NotImplemented.__reduce__` — #3738
- [x] `types.SimpleNamespace.__reduce__` #4975 

These listed elements are almost similar and quite simple to implement.
Please take a look at many PR and existing codes for `__reduce__`

**Comment by youknowone** [comment]
itertools pickle is going to be deprecated https://github.com/python/cpython/issues/101588

**Comment by youknowone** [comment]
Since all of remaining checklist is about itertools, I am going to close this issue.
Thank you so much everyone who worked on this issue!
