### ISSUE TITLE
Update python libraries and tests from CPython 3.11

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#4564]
Though it will be sometimes blocked by rust side issues, don't worry!
Please just create PR about the broken test and and create issues related to the new bugs.

If you are new to updating cpython libraries, this guide will be useful:
https://github.com/RustPython/RustPython/wiki/How-to-update-test-files

When updating module Lib/X, please don't forget to also update Lib/test/test_X

A few libraries doesn't need to be updated because CPython also kept it same as previous version. In that case, please leave a comment to let us mark it as done. Thank you!

Tips
- To get specific version of CPython source code, try `git checkout v3.11.2` from CPython repository.
- Please check #4064 for example. Not the entire changes but the each commits. One of the middle size example is https://github.com/RustPython/RustPython/commit/17e12dea1ec11b871a9e5d3a4a26e2f9ad83fde2 . Sometimes it can be really simple like https://github.com/RustPython/RustPython/pull/4064/commits/9571a68c01284191d4b18229694c303dad8992ff
- Please create one PR for one library+test pair whenever possible. Once you stuck by dependencies, go to one of the dependency first and finish it before restarting the stuck one unless they become simpler to be updated at the same time. Normally adding more libraries make passing tests (a lot) harder.
- To run tests, try `cargo run --features ssl -- -m test -v <test_name>`. e.g. If you changed `test_unicode.py`, `cargo run --features ssl -- -m test -v test_unicode`
  - If it runs too slow, try to add `--release` like `cargo run --release --features ssl -- -m test -v test_unicode`

# List of libraries
- [ ] `__future__.py`
  - [ ] maybe related to #4060?
- [x] `__hello__.py` #4570
- [x] `__phello__` #4570
- [x] `_collections_abc.py`https://github.com/RustPython/RustPython/pull/5016
- [ ] `_compat_pickle.py`
- [x] `_compression.py` #4688 
- [x] `_markupbase.py` #4703
- [x] ~~`_osx_support.py`~~ unchanged
  - [x] #4670
- [ ] `_py_abc.py`
- [ ] `_pycodecs.py`
- [ ] `_pydecimal.py`
- [ ] `_pyio.py`
- [ ] `_sitebuiltins.py`
- [ ] `_threading_local.py`
- [ ] `_weakrefset.py`
- [x] `abc.py` #4985 
- [x] `aifc.py`
- [x] `antigravity.py` — #4591 
- [x] `argparse.py` — #4592 
- [ ] `ast.py`
- [ ] `asynchat.py`
- [ ] `asyncio`
  - [ ] #3118
  - [ ] #3859
- [ ] `asyncore.py`
- [x] `base64.py` Commit https://github.com/RustPython/RustPython/pull/4777/commits/185111d197112d547e02d88441cbced1ce5abe4b
- [ ] `bdb.py`
- [x] ~~`binhex.py`~~ Deprecated.
- [x] `bisect.py` #4774
- [x] `bz2.py` Unchanged
- [x] `calendar.py` #4669
- [x] `cgi.py`
- [x] `cgitb.py`
- [x] `chunk.py`
- [x] `cmd.py`
- [x] `code.py`
- [ ] `codecs.py`
  - See also #3861
- [x] `codeop.py`
- [ ] `collections`
  - See also #3418
- [x] `colorsys.py`
- [x] `compileall.py` #5070
- [ ] `concurrent`
- [x] `configparser.py` #4595
- [x] `contextlib.py` #4649 #4659
- [ ] `contextvars.py`
  - [ ] #3188
- [x] `copy.py` https://github.com/RustPython/RustPython/pull/4674
- [ ] `copyreg.py`
- [ ] `csv.py`
- [ ] `ctypes`
  - [ ] #1217
  - See also #2364
- [ ] `dataclasses.py` pending `match` statement support.
- [ ] `datetime.py`
- [ ] `dbm`
- [ ] `decimal.py`
- [x] `difflib.py` #5063
- [ ] `dis.py`
  - see also #3846
- [ ] `distutils`
- [ ] `doctest.py`
- [ ] `email`
- [ ] `encodings`
- [x] `ensurepip` #4590
- [x] `enum.py` #5074
- [ ] `filecmp.py`
- [x] `fileinput.py` #5071
- [ ] `fnmatch.py`
- [x] ~~`formatter.py`~~ Deprecated
- [x] `fractions.py` #5072
- [x] `ftplib.py` #5073
- [ ] `functools.py`
- [ ] `gc.py`
  - #4158
- [ ] `genericpath.py`
- [ ] `getopt.py`
- [ ] `getpass.py`
- [ ] `gettext.py`
- [x] `glob.py`  #4744
- [ ] `graphlib.py`
- [x] `gzip.py` #4688 
- [x] `hashlib.py`
- [x] `heapq.py`
- [x] `hmac.py` unchanged
- [x] `html`
  - [x] html/parser #4703
  - test_html is unchanged
- [ ] `http`
- [x] `imghdr.py`
- [x] `imp.py`
- [x] `importlib` #4561
  - [x] #4559
  - #4565
- [ ] `inspect.py`
- [ ] `io.py`
  - [ ] #3960
  - [x] #4662
  - See also #4072
- [x] `ipaddress.py`
- [ ] `json`
- [x] `keyword.py` unchanged
- [x] `linecache.py`
- [x] `locale.py` #4537
  - See also #3850
- [ ] `logging`
- [ ] `mailbox.py`
  - [ ] #4072
- [ ] `mimetypes.py`
- [ ] `multiprocessing`
  - See also #3965
- [x] `netrc.py`
- [x] `nntplib.py`
- [x] `ntpath.py`
- [x] `nturl2path.py`
- [x] `numbers.py`
- [ ] `opcode.py`
- [x] ~`operator.py`~ unchanged
- [x] `optparse.py` unchanged
- [ ] `os.py`
  - [ ] #3960
  - See also #4053
- [ ] `pathlib.py`
  - [ ] #3960
- [ ] `pdb.py`
- [ ] `pickle.py`
  - See also #3876
- [ ] `pickletools.py`
- [ ] `pkgutil.py`
- [ ] `platform.py`
- [ ] `plistlib.py`
- [ ] `posixpath.py`
- [x] `pprint.py`
- [ ] `pty.py`
- [ ] `py_compile.py`
- [ ] `pydoc.py`
  - [ ] `pydoc_data`
- [ ] `queue.py`
  - See also #3608 
- [ ] `quopri.py`
- [x] `random.py` #4748
- [ ] `re.py`
- [ ] `reprlib.py`
- [ ] `rlcompleter.py`
- [ ] `runpy.py`
- [ ] `sched.py`
- [ ] `secrets.py`
- [ ] `selectors.py`
- [ ] `shelve.py`
- [ ] `shlex.py`
- [ ] `shutil.py`
  - [ ] #3960
- [ ] `signal.py`
- [x] `site.py`
  - [x] #4789
  - [x] #4662
  - #4550
- [ ] `smtpd.py`
- [ ] `smtplib.py`
- [ ] `sndhdr.py`
- [ ] `socket.py`
- [ ] `socketserver.py`
- [ ] `sqlite3`
- [ ] `sre_compile.py`
- [ ] `sre_constants.py`
- [ ] `sre_parse.py`
- [ ] `ssl.py`
  - See also #3927
- [ ] `stat.py`
- [ ] `statistics.py`
- [ ] `string.py`
- [ ] `stringprep.py`
- [ ] `struct.py`
- [ ] `subprocess.py` #4981
- [ ] `sunau.py`
- [x] `sysconfig.py` #4569
- [ ] `tabnanny.py`
- [ ] `tarfile.py`
- [ ] `telnetlib.py`
- [ ] `tempfile.py`
- [ ] `textwrap.py`
- [ ] `this.py`
- [ ] `threading.py`
- [ ] `timeit.py`
- [ ] `token.py`
- [ ] `tokenize.py`
- [ ] `tomllib`
- [x] `trace.py` #4586
- [ ] `traceback.py`
- [ ] `tty.py`
- [ ] `types.py`
- [ ] `typing.py`
- [x] `unittest`  #4560
- [ ] `urllib`
- [ ] `uu.py`
- [ ] `uuid.py`
- [ ] `venv`
  - [ ] #3960
- [ ] `warnings.py`
  - [ ] #4013
- [ ] `weakref.py`
- [ ] `webbrowser.py`
- [ ] `wsgiref`
- [ ] `xdrlib.py`
- [ ] `xml`
- [ ] `xmlrpc`
- [ ] `zipapp.py`
- [ ] `zipfile.py`
- [ ] `zipimport.py`
- [x] test.support #4537
  - [x] #4540 
  - [ ] #4538
  - [x] #4539 
  - [ ] #4541

# List of tests without python libraries
- [ ] `test/test___all__.py`
- [ ] `test/test__locale.py`
- [ ] `test/test__opcode.py`
- [ ] `test/test_abstract_numbers.py`
- [x] `test/test_array.py`  #4745
  - See also #3876
- [ ] `test/test_asdl_parser.py`
- [ ] `test/test_asyncgen.py`
  - [ ] #3859
- [x] `test/test_atexit.py` #4621
- [ ] `test/test_audioop.py`
- [ ] `test/test_audit.py`
- [x] ~~`test/test_augassign.py`~~ _unchanged_
- [x] `test/test_baseexception.py` — #4624
- [ ] `test/test_bigaddrspace.py`
- [x] `test/test_bigmem.py` #4625
- [ ] `test/test_binascii.py`
  - See also #4374
- [x] ~~`test/test_binop.py`~~ _unchanged_
- [x] `test/test_bool.py` #4631
- [x] `test/test_buffer.py` #4632
- [x] ~~`test/test_bufio.py`~~ _unchanged_
- [x] `test/test_builtin.py` #4765 
- [x] `test/test_bytes.py` #4746
- [ ] `test/test_bz2.py`
- [ ] `test/test_c_locale_coercion.py`
- [ ] `test/test_call.py`
- [x] ~~`test/test_charmapcodec.py`~~ unchanged 
- [ ] `test/test_check_c_globals.py`
- [ ] `test/test_class.py`
- [ ] `test/test_clinic.py`
- [x] ~~`test/test_cmath.py`~~ unchanged
- [x] `test/test_cmd_line.py` #4801 
- [x] `test/test_cmd_line_script.py` #4802 
- [x] ~~`test/test_code_module.py`~~ unchanged
- [x] ~~`test/test_codeccallbacks.py`~~ unchanged
- [x] `test/test_compare.py` #4803
- [x] `test/test_compile.py` #4804 
- [x] `test/test_complex.py`  #4755
- [x] ~`test/test_contains.py`~ unchanged
- [x] `test/test_context.py` #4805 
- [ ] `test/test_contextlib_async.py`
- [ ] `test/test_coroutines.py`
- [x] ~~`test/test_crashers.py` #4807~~ CPython specific
- [ ] `test/test_csv.py`
- [x] `test/test_decorators.py` #4806 
- [x] ~~`test/test_defaultdict.py`~~ unchanged
- [x] `test/test_deque.py` #4761 
- [x] ~~`test/test_descr.py`~~ unchanged
- [ ] `test/test_descrtut.py`
- [x] `test/test_devpoll.py` #4808 
- [x] `test/test_dict.py` #4763
- [x] ~~`test/test_dict_version.py` #4809~~ Not implemented in RustPython 
- [x] ~~`test/test_dictcomps.py`~~ unchanged
- [x] `test/test_dictviews.py` #4810 
- [x] `test/test_docxmlrpc.py` #4811 
- [x] `test/test_dtrace.py` #4812 
- [x] `test/test_dynamic.py` #4813 
- [x] ~~`test/test_dynamicclassattribute.py`~~ unchanged
- [x] `test/test_eintr.py` #4814 
- [x] ~~`test/test_embed.py` #4815~~ CPython specific. 
- [ ] `test/test_enumerate.py` 
- [x] `test/test_eof.py`  #4753
- [x] `test/test_epoll.py` #4816 
- [x] ~~`test/test_errno.py`~~ unchanged
- [ ] `test/test_except_star.py`
- [x] `test/test_exception_group.py` #4817 
- [x] `test/test_exception_hierarchy.py` #4818 
- [ ] `test/test_exception_variations.py` 
- [x] `test/test_exceptions.py` #4819 
- [ ] `test/test_extcall.py`
- [x] `test/test_faulthandler.py` #4820 
- [x] ~~`test/test_fcntl.py`~~ unchanged
- [x] ~~`test/test_file.py`~~ unchanged
- [ ] `test/test_file_eintr.py`
- [x] `test/test_fileio.py` #4821 
- [x] ~~`test/test_fileutils.py` #4822~~ CPython specific
- [ ] `test/test_finalization.py` 
- [x] `test/test_float.py` #4823 
- [x] ~~`test/test_flufl.py` #4824~~ CPython specific 
- [ ] `test/test_fork1.py`
- [x] `test/test_format.py` #4825 
- [ ] `test/test_frame.py`
- [ ] `test/test_frozen.py`
- [ ] `test/test_fstring.py`
- [x] `test/test_funcattrs.py` #4829 
- [x] `test/test_future.py` #4830
- [x] ~~`test/test_future3.py`~~ unchanged
- [x] ~~`test/test_future4.py`~~ unchanged
- [x] ~~`test/test_future5.py`~~ unchanged
- [ ] `test/test_gdb.py`
- [ ] `test/test_generator_stop.py`
- [ ] `test/test_generators.py`
- [x] `test/test_genericalias.py` #4831
- [ ] `test/test_genericclass.py`
- [ ] `test/test_genexps.py`
- [ ] `test/test_getpath.py`
- [x] `test/test_global.py` #4832
- [ ] `test/test_grammar.py`
- [x] `test/test_grp.py` #4833
- [x] `test/test_hash.py` #4834
- [x] `test/test_hashlib.py` #4835
- [x] ~~`test/test_index.py`~~ unchanged
- [ ] `test/test_int.py`
- [x] ~`test/test_int_literal.py`~ unchanged
- [ ] `test/test_interpreters.py`
- [x] ~~`test/test_ioctl.py`~~ unchanged
- [x] ~~`test/test_isinstance.py`~~ unchanged
- [ ] `test/test_iter.py`
  - [ ] #3960
- [x] ~~`test/test_iterlen.py`~~ unchanged
- [x] `test/test_itertools.py` #4836
- [x] ~~`test/test_keywordonlyarg.py`~~ unchanged
- [x] `test/test_kqueue.py` #4837
- [x] `test/test_largefile.py` #4838
- [x] ~~`test/test_launcher.py`~~ CPython specific
- [x] `test/test_list.py`
  - See also #1750, #4839
- [x] `test/test_listcomps.py` #4757
- [ ] `test/test_lltrace.py`
- [x] `test/test_long.py` #4840
- [x] ~~`test/test_longexp.py`~~ unchanged
- [ ] `test/test_marshal.py`
  - See also #3458
- [x] `test/test_math.py` #4754
- [x] ~~`test/test_memoryio.py`~~ unchanged
- [x] ~~`test/test_memoryview.py`~~ unchanged
- [ ] `test/test_metaclass.py`
- [ ] `test/test_minidom.py`
- [x] `test/test_mmap.py`
  - See also #3847, #4841
- [x] `test/test_module.py` #4842 
- [ ] `test/test_multibytecodec.py`
- [x] ~~`test/test_named_expressions.py`~~ unchanged
- [ ] `test/test_nis.py`
- [x] `test/test_numeric_tower.py` #4843 
- [x] `test/test_opcache.py` #4844 
- [x] ~~`test/test_openpty.py`~~ unchanged
- [x] `test/test_ordered_dict.py` #4846 
- [ ] `test/test_ossaudiodev.py`
- [ ] `test/test_osx_env.py`
- [ ] `test/test_patma.py`
- [ ] `test/test_peepholer.py`
- [ ] `test/test_pep646_syntax.py`
- [ ] `test/test_picklebuffer.py`
- [ ] `test/test_pkg.py`
- [ ] `test/test_poll.py` #4888
- [x] `test/test_popen.py` #4889
- [ ] `test/test_positional_only_arg.py`
- [x] `test/test_posix.py`#4890
  - See also #4494
- [x] `test/test_pow.py` #4891
- [x] `test/test_print.py` #4778
- [ ] `test/test_property.py` #4892
  - See also #4067
- [ ] `test/test_pulldom.py` #4893
- [ ] `test/test_pwd.py`
- [ ] `test/test_pyexpat.py`
  - See also #3430
- [ ] `test/test_raise.py`
- [ ] `test/test_range.py`
- [ ] `test/test_readline.py`
- [ ] `test/test_regrtest.py`
- [ ] `test/test_repl.py`
- [ ] `test/test_resource.py`
- [ ] `test/test_richcmp.py`
- [ ] `test/test_robotparser.py`
- [ ] `test/test_sax.py`
- [ ] `test/test_scope.py`
- [ ] `test/test_script_helper.py`
- [ ] `test/test_select.py`
- [ ] `test/test_set.py`
  - See also #3992
- [ ] `test/test_setcomps.py`
- [ ] `test/test_slice.py`
- [ ] `test/test_smtpnet.py`
- [x] `test/test_sort.py`  #4749
- [ ] `test/test_source_encoding.py`
- [ ] `test/test_spwd.py`
- [ ] `test/test_stable_abi_ctypes.py`
- [ ] `test/test_startfile.py`
- [ ] `test/test_strftime.py`
- [x] `test/test_string.py` #4751
- [ ] `test/test_string_literals.py`
- [ ] `test/test_strptime.py`
- [ ] `test/test_strtod.py`
- [ ] `test/test_structseq.py`
 -  See also #4063
- [ ] `test/test_subclassinit.py`
- [ ] `test/test_sundry.py`
- [ ] `test/test_super.py`
  - See also #3865
- [x] `test/test_support.py`
  - [ ] #4538
  - [x] #4539
- [x] `test/test_syntax.py` #4602 
  - [ ] #4479
- [x] `test.test_sys` #4569
  - [x] #4123
  - See also #3859
  - See also #4541
- [ ] `test/test_sys_setprofile.py`
- [ ] `test/test_sys_settrace.py`
- [x] `test/test_syslog.py` #4569
- [ ] `test/test_tcl.py`
- [ ] `test/test_thread.py`
- [ ] `test/test_threadedtempfile.py`
- [ ] `test/test_threadsignals.py`
- [ ] `test/test_time.py`
  - See also #3850
  - See also #4157
- [ ] `test/test_timeout.py`
- [ ] `test/test_tix.py`
- [ ] `test/test_tuple.py`
- [ ] `test/test_type_annotations.py`
- [ ] `test/test_type_cache.py`
- [ ] `test/test_type_comments.py`
- [ ] `test/test_typechecks.py`
- [x] `test/test_types.py` #4683
- [ ] `test/test_ucn.py`
- [ ] `test/test_unary.py`
- [ ] `test/test_unicode.py`
- [ ] `test/test_unicode_file.py`
- [x] `test/test_unicode_file_functions.py` #4741
- [x] ~~`test/test_unicode_identifiers.py`~~
- [x] `test/test_unicodedata.py` #4678
- [x] ~~`test/test_univnewlines.py`~~ _unchanged_
- [x] `test/test_unpack.py` #4676 
- [ ] `test/test_unpack_ex.py`
- [ ] `test/test_unparse.py`
- [x] `test/test_userdict.py` #4666
- [x] `test/test_userlist.py` #4666
- [x] `test/test_userstring.py` #4658
- [x] ~~`test/test_utf8_mode.py`~~ _unchanged_
- [x] ~~`test/test_utf8source.py`~~ _unchanged_
- [ ] `test/test_wait3.py`
- [ ] `test/test_wait4.py`
- [x] `test/test_weakset.py` #4657
- [ ] `test/test_winconsoleio.py`
- [ ] `test/test_winreg.py`
- [ ] `test/test_winsound.py`
- [x] `test/test_with.py` #4648
- [x] ~~`test/test_yield_from.py`~~ _unchanged_
- [x] `test/test_zlib.py` #4647
- [ ] `test/test_asyncio`
- [ ] `test/test_capi`
- [x] `test/test_import` #4599
- [ ] `test/test_tools`

# Not yet added libraries
These libraris are not added yet. Pure python one will be possible while others are not.

- [ ] `_bootsubprocess.py`
- [ ] `_pycodecs.py`
- [ ] `cProfile.py`
- [ ] `crypt.py`
- [ ] `curses`
- [ ] `idlelib`
- [ ] `imaplib.py`
- [ ] `imp.py`
  - [ ] See also #4075
- [ ] `lzma.py`
- [ ] `mailcap.py`
- [ ] `modulefinder.py`
  - [ ] #3846 
- [ ] `msilib`
- [ ] `pipes.py`
- [ ] `poplib.py`
- [ ] `pstats.py`
- [ ] `pyclbr.py`
- [ ] `symtable.py`
- [ ] `tkinter`
- [ ] `tracemalloc.py`
- [ ] `turtle.py`
- [ ] `wave.py`
- [ ] `zoneinfo`

**Comment by fanninpm** [comment]
Updating `asyncio` is going to require fleshing out `contextvars`. (See #3188.)

**Comment by DimitrisJim** [comment]
Pasting the comment (https://github.com/RustPython/RustPython/pull/4592#pullrequestreview-1318321535) here too for anyone else who might need it:

You can use the following command to test your changes locally (in a manner similar to RustPython's CI):

```shell
# this runs all of the tests (not necessary if you know which test is affected)
cargo run --release --features ssl,jit -- -m test -j 1 -u all --slowest --fail-env-changed -v
# this runs only the test suite named "test_whatever" (usually located at `Lib/test/test_whatever.py`)
cargo run --release --features ssl,jit -- -m test -j 1 -u all --slowest --fail-env-changed -v test_whatever
```

For a list of all resources and more command-line options, you can execute `cargo run --release --features ssl,jit -- -m test -h`

**Comment by dalinaum** [comment]
`test/test_binop.py` is unchanged.

**Comment by dalinaum** [comment]
`test/test_utf8source.py` is unchanged.
`test/test_utf8_mode.py is unchanged.

**Comment by dalinaum** [comment]
`test_univnewlines.py` remains unchanged.

**Comment by tdub0** [comment]
`test_html.py` and `test_htmlparser.py` remain unchanged.

**Comment by dalinaum** [comment]
`test_unicode_identifiers.py` remains unchanged.

**Comment by JaeyoungAhn** [comment]
test_contains remain unchanged.

**Comment by Snowapril** [comment]
test_int_literal.py remain unchanged

**Comment by jyj0816** [comment]
`test_operators.py` remain unchanged.
`operators.py` remain unchanged.

**Comment by Masorubka1** [comment]
test_file.py test_charmapcodec.py test_cmath.py test_code_module.py test_codeccallbacks.py test_defaultdict.py test_descr.py test_dictcomps.py test_dynamicclassattribute.py test_errno.py test_fcntl.py test_file.py - unchanged

**Comment by Masorubka1** [comment]
test_future3.py test_future4.py test_future5.py test_index.py test_ioctl.py test_isinstance.py test_iterlen.py test_keywordonlyarg.py test_longexp.py  test_memoryio.py  test_memoryview.py test_named_expressions.py test_openpty.py - unchanged

test_launcher.py - Cpython specific

**Comment by MegasKomnenos** [comment]
bisect.py was updated in https://github.com/RustPython/RustPython/pull/4774 , but its corresponding check box is unchecked

**Comment by youknowone** [comment]
Thanks to everyone who participated in this series of patches! I am going to close this issue in favor of #5104
