### ISSUE TITLE
Update Python libraries and tests from CPython 3.12

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#5104]
Though it will be sometimes blocked by rust side issues, don't worry!
Please just create PR about the broken test and and create issues related to the new bugs.

If you are new to updating cpython libraries, this guide will be useful:
https://github.com/RustPython/RustPython/wiki/How-to-update-test-files

When updating module Lib/X, please don't forget to also update Lib/test/test_X

A few libraries doesn't need to be updated because CPython also kept it same as previous version. In that case, please leave a comment to let us mark it as done. Thank you!

Tips
- To get specific version of CPython source code, e.g. try `git checkout v3.12.0` from CPython repository.
- Please check #4064 for example. Not the entire changes but the each commits. One of the middle size example is https://github.com/RustPython/RustPython/commit/17e12dea1ec11b871a9e5d3a4a26e2f9ad83fde2 . Sometimes it can be really simple like https://github.com/RustPython/RustPython/pull/4064/commits/9571a68c01284191d4b18229694c303dad8992ff
- Please create one PR for one library+test pair whenever possible. Once you stuck by dependencies, go to one of the dependency first and finish it before restarting the stuck one unless they become simpler to be updated at the same time. Normally adding more libraries make passing tests (a lot) harder.
- To run tests, try `cargo run --features ssl -- -m test -v <test_name>`. e.g. If you changed `test_unicode.py`, `cargo run --features ssl -- -m test -v test_unicode`
  - If it runs too slow, try to add `--release` like `cargo run --release --features ssl -- -m test -v test_unicode`

# List of libraries
- [x] `__future__.py` #5257
  - Related test is  `test_future_stmt`
  - [ ] maybe related to #4060?
- [x] `__hello__.py` unchanged
- [x] `__phello__` unchanged
- [x] `_compression.py` unchanged
- [x] `_markupbase.py` unchanged
- [x] `_osx_support.py` unchanged
- [ ] `_threading_local.py`
- [ ] `_weakrefset.py`
- [x] `abc.py` #5134 
  - `_collections_abc.py`
  - `_py_abc.py`
- [x] `aifc.py` removed in 3.13
- [x] `antigravity.py` unchanged
- [x] `argparse.py` #5134 
- [x] `ast.py` #5121
- [x] `asynchat.py` #5134  removed in 3.13
- [x] `asyncio` #3858
  - [x] #3859
  - requires `_contextvars`
  - requires `_overlapped` for windows
- [x] `asyncore.py` #5134  removed in 3.13
- [x] `base64.py` #5134 
- [x] `bdb.py` #5134 
- [x] `bisect.py` #5134 
- [x] `bz2.py` #5134 
- [x] `calendar.py` #5169 
- [x] `cgi.py` removed in 3.13
- [x] `cgitb.py` #5197   removed in 3.13
- [x] `chunk.py`  removed in 3.13
- [x] `cmd.py` unchanged
- [x] `code.py` #5174 
  - `test_code_module` is related test
- [x] `codecs.py`  #5372
  - [ ] `_pycodecs.py`
  - See also #3861
- [x] `codeop.py`  #5115
- [ ] `collections`
  - See also #3418
- [x] `colorsys.py` #5198
- [ ] `compileall.py` #5199
- [ ] `concurrent`
- [ ] `configparser.py` #5172
- [ ] `contextlib.py`
- [x] `contextvars.py` unchanged
  - [x] #3188
- [x] `copy.py` #5175 
- [x] `copyreg.py` #5342 #5200
  - requires `__getstate__`
- [x] `csv.py` #5176
- [ ] `ctypes`
  - [ ] #1217
  - See also #2364
- [ ] `dataclasses.py` #5377 pending `match` statement support.
- [x] `datetime.py` #5314
  - `_pydatetime.py`
- [ ] `dbm`
- [x] `decimal.py`  #5078
  - [ ] `_pydecimal.py` - depending on `contextvars`
- [ ] `difflib.py`
- [ ] `dis.py`
  - see also #3846
- [ ] `distutils`
- [ ] `doctest.py` - depending on `_io.IncrementalNewlineDecoder`
- [ ] `email`
- [x] `encodings`  #5253
- [x] `ensurepip`  #5108
- [x] `enum.py` #5078
- [x] `filecmp.py` #5258
- [ ] `fileinput.py`
- [ ] `fnmatch.py`
- [x] `fractions.py` #5375
- [x] `ftplib.py` #5196
- [x] `functools.py` #5078
- [ ] `gc.py`
  - #4158
- [x] `genericpath.py`
- [x] `getopt.py`  #5253
- [ ] `getpass.py`
- [x] `gettext.py` #5287
- [x] `glob.py` #5253
- [x] `graphlib.py` unchanged
- [ ] `gzip.py` #5480
- [ ] `hashlib.py`
- [x] `heapq.py` unchanged
- [x] `hmac.py` #5188 
- [ ] `html`
- [ ] `http`
- [x] `imghdr.py`  removed in 3.13
- [ ] `imp.py` removed in 3.12
- [x] `importlib` #5078
  - #4565
- [x] `inspect.py` #5377
- [x] `io.py` #5370
  - [x] `_pyio.py` #5370
  - [ ] #3960
  - See also #4072
- [x] `ipaddress.py` #5312
- [ ] `json`
- [ ] `keyword.py`
- [ ] `linecache.py`
- [ ] `locale.py`
  - See also #3850
- [x] `logging` #5478
- [ ] `mailbox.py`
  - [ ] #4072
- [ ] `mimetypes.py`
- [x] `multiprocessing` #5263
  - See also #3965
- [ ] `netrc.py`
- [x] `nntplib.py`  removed in 3.13
- [x] `ntpath.py` #5262
- [ ] `nturl2path.py`
- [ ] `numbers.py`
- [x] `opcode.py` #5115
- [x] `operator.py` #5194
- [ ] `optparse.py`
- [x] `os.py` #5257 #5310
  - Blocker: Some tests requires async comprehension
  - [ ] #3960
  - See also #4053
- [x] `pathlib.py` #5311
  - [ ] #3960
- [ ] `pdb.py`
- [x] `pickle.py` #5260
  - See also #3876
  - `_compat_pickle.py`
  - [x] `test/pickletester.py` supports `test_pickle.py` #5260
  - [ ] `test/test_picklebuffer.py`
- [x] `pickletools.py` #5260
- [ ] `pkgutil.py`
- [ ] `platform.py`
- [ ] `plistlib.py`
- [x] `posixpath.py` #5257
- [x] `pprint.py` #5195
- [ ] `pty.py`
- [ ] `py_compile.py`
- [ ] `pydoc.py`
  - [ ] `pydoc_data`
- [ ] `queue.py`
  - See also #3608 
- [ ] `quopri.py`
- [ ] `random.py`
- [x] `re.py` #5125
  - Don't forget sre files `sre_compile.py`, `sre_constants.py`, `sre_parse.py`
- [ ] `reprlib.py`
- [ ] `rlcompleter.py`
- [ ] `runpy.py`
- [ ] `sched.py`
- [ ] `secrets.py`
- [x] `selectors.py` #5290
- [ ] `shelve.py`
- [ ] `shlex.py`
- [x] `shutil.py` #5228
  - [ ] #3960
- [x] `signal.py` #5280
- [x] `site.py` #5313
  - Don't forget `_sitebuiltins.py`
- [x] `smtpd.py`  removed in 3.13
- [x] `smtplib.py` #5478
- [x] `sndhdr.py`  removed in 3.13
- [ ] `socket.py`
- [ ] `socketserver.py`
- [ ] `sqlite3`
- [ ] `ssl.py`
- [ ] `stat.py`
- [ ] `statistics.py`
- [ ] `string.py`
- [ ] `stringprep.py`
- [ ] `struct.py`
- [x] `subprocess.py` #5290
- [x] `sunau.py`  removed in 3.13
- [ ] `sysconfig.py`
- [ ] `tabnanny.py`
- [ ] `tarfile.py`
- [x] `telnetlib.py`  removed in 3.13
- [ ] `tempfile.py`
- [ ] `textwrap.py`
- [x] `this.py`
- [ ] `threading.py`
- [ ] `timeit.py`
- [ ] `token.py`
- [ ] `tokenize.py`
- [ ] `tomllib`
- [ ] `trace.py`
- [ ] `traceback.py`
- [ ] `tty.py`
- [ ] `types.py`
- [ ] `typing.py` #5149
- [x] `unittest`  #5078
- [ ] `urllib`
- [x] `uu.py` #5161   removed in 3.13
- [ ] `uuid.py`
- [ ] `venv`
  - [ ] #3960
- [ ] `warnings.py`
  - [ ] #4013
- [ ] `weakref.py`
- [ ] `webbrowser.py`
- [ ] `wsgiref`
- [x] `xdrlib.py`  removed in 3.13
- [ ] `xml`
- [ ] `xmlrpc`
- [ ] `zipapp.py`
- [ ] `zipfile.py`
- [ ] `zipimport.py`
- [ ] test.support #5078
  - [ ] #4538
  - [ ] #4541

# List of tests without python libraries
- [ ] `test/test___all__.py`
- [x] `test/test__locale.py` #5114
- [ ] `test/test__opcode.py`
- [ ] `test/test_abstract_numbers.py`
- [ ] `test/test_array.py` 
  - See also #3876
- [ ] `test/test_asdl_parser.py`
- [ ] `test/test_asyncgen.py`
  - [x] #3859
- [x] `test/test_atexit.py` #5114
- [ ] `test/test_audioop.py`
- [ ] `test/test_audit.py`
- [ ] `test/test_augassign.py`
- [ ] `test/test_baseexception.py`
- [x] `test/test_bigaddrspace.py` #5122
- [x] `test/test_bigmem.py` #5122
- [ ] `test/test_binascii.py`
- [x] `test/test_binop.py` unchanged
- [x] `test/test_bool.py` #5122
- [ ] `test/test_buffer.py`
- [x] `test/test_bufio.py` #5122
- [ ] `test/test_builtin.py`
- [ ] `test/test_bytes.py`
- [ ] `test/test_bz2.py`
- [x] `test/test_c_locale_coercion.py` #5122
- [ ] `test/test_call.py`
- [ ] `test/test_charmapcodec.py` 
- [ ] `test/test_check_c_globals.py`
- [x] `test/test_class.py` #5122
- [ ] `test/test_clinic.py`
- [x] `test/test_cmath.py` #5122
- [x] `test/test_cmd_line.py`  #5127
- [x] `test/test_cmd_line_script.py` #5127
- [x]  `test/test_codeccallbacks.py` unchanged
- [x] `test/test_compare.py` #5127
- [x] `test/test_compile.py` #5251
- [x] `test/test_complex.py` #5127
- [x] `test/test_contains.py` unchanged
- [x] `test/test_context.py` #5127
- [ ] `test/test_contextlib_async.py`
- [ ] `test/test_coroutines.py`
- [x] `test/test_crashers.py` #4807 CPython specific
- [ ] `test/test_csv.py` #5176
- [x] `test/test_decorators.py`  #5127
- [x] `test/test_defaultdict.py` #5127
- [x] `test/test_deque.py` unchanged
- [x] `test/test_descr.py`#5127
- [x] `test/test_descrtut.py` #5127
- [x] `test/test_devpoll.py` unchanged
- [x] `test/test_dict.py` #5127
- [x] `test/test_dict_version.py` #4809 Not implemented in RustPython 
- [x] `test/test_dictcomps.py` unchanged
- [x] `test/test_dictviews.py` #5127
- [x] `test/test_docxmlrpc.py` unchanged
- [x] `test/test_dtrace.py` #5127
- [x] `test/test_dynamic.py` #5127
- [x] `test/test_dynamicclassattribute.py` unchanged
- [x] `test/test_eintr.py` #5127
- [ ] `test/test_embed.py`
- [ ] `test/test_enumerate.py` 
- [x] `test/test_eof.py` #5127
- [x] `test/test_epoll.py` #5127
- [x] `test/test_errno.py` unchanged
- [ ] `test/test_except_star.py`
- [ ] `test/test_exception_group.py` #5254
- [x] `test/test_exception_hierarchy.py`  unchanged
- [ ] `test/test_exception_variations.py` 
- [ ] `test/test_exceptions.py`
- [ ] `test/test_extcall.py`
- [ ] `test/test_faulthandler.py`
- [ ] `test/test_fcntl.py`
- [x] `test/test_file.py` #5134 
- [ ] `test/test_file_eintr.py`
- [ ] `test/test_fileio.py`
- [ ] `test/test_fileutils.py`
- [ ] `test/test_finalization.py` 
- [ ] `test/test_float.py`
- [x] `test/test_flufl.py` #4824 CPython specific 
- [ ] `test/test_fork1.py`
- [ ] `test/test_format.py`
- [ ] `test/test_frame.py`
- [ ] `test/test_frozen.py`
- [ ] `test/test_fstring.py`
- [ ] `test/test_funcattrs.py`
- [ ] `test/test_future.py`
- [ ] `test/test_future3.py`
- [ ] `test/test_future4.py`
- [ ] `test/test_future5.py`
- [ ] `test/test_gdb.py`
- [ ] `test/test_generator_stop.py`
- [ ] `test/test_generators.py`
- [ ] `test/test_genericalias.py`
- [ ] `test/test_genericclass.py`
- [ ] `test/test_genexps.py`
- [ ] `test/test_getpath.py`
- [ ] `test/test_global.py`
- [ ] `test/test_grammar.py`
- [ ] `test/test_grp.py`
- [ ] `test/test_hash.py`
- [ ] `test/test_hashlib.py`
- [ ] `test/test_index.py`
- [ ] `test/test_int.py`
- [x] `test/test_int_literal.py` (unchanged)
- [ ] `test/test_interpreters.py`
- [ ] `test/test_ioctl.py`
- [ ] `test/test_isinstance.py`
- [ ] `test/test_iter.py`
  - [ ] #3960
- [ ] `test/test_iterlen.py`
- [x] `test/test_itertools.py` #5209
- [ ] `test/test_keywordonlyarg.py`
- [ ] `test/test_kqueue.py`
- [ ] `test/test_largefile.py`
- [ ] `test/test_launcher.py`
- [ ] `test/test_list.py`
  - See also #1750
- [ ] `test/test_listcomps.py` 
- [ ] `test/test_lltrace.py`
- [ ] `test/test_long.py` 
- [ ] `test/test_longexp.py`
- [ ] `test/test_marshal.py`
  - See also #3458
- [x] `test/test_math.py` #5507
- [ ] `test/test_memoryio.py`
- [ ] `test/test_memoryview.py`
- [ ] `test/test_metaclass.py`
- [ ] `test/test_minidom.py`
- [ ] `test/test_mmap.py`
  - See also #3847
- [x] `test/test_module.py` #5078 
- [ ] `test/test_multibytecodec.py`
- [ ] `test/test_named_expressions.py`
- [ ] `test/test_nis.py`
- [x] `test/test_numeric_tower.py`
- [ ] `test/test_opcache.py` 
- [ ] `test/test_openpty.py`
- [ ] `test/test_ordered_dict.py` 
- [ ] `test/test_ossaudiodev.py`
- [ ] `test/test_osx_env.py`
- [ ] `test/test_patma.py`
- [ ] `test/test_peepholer.py`
- [ ] `test/test_pep646_syntax.py`
- [ ] `test/test_pkg.py`
- [ ] `test/test_poll.py`
- [ ] `test/test_popen.py`
- [ ] `test/test_positional_only_arg.py`
- [ ] `test/test_posix.py` #5257
  - See also #4494
- [ ] `test/test_pow.py`
- [ ] `test/test_print.py`
- [ ] `test/test_property.py` 
  - See also #4067
- [ ] `test/test_pulldom.py`
- [ ] `test/test_pwd.py`
- [ ] `test/test_pyexpat.py`
  - See also #3430
- [ ] `test/test_raise.py`
- [ ] `test/test_range.py`
- [ ] `test/test_readline.py`
- [ ] `test/test_regrtest.py`
- [ ] `test/test_repl.py`
- [ ] `test/test_resource.py`
- [ ] `test/test_richcmp.py`
- [ ] `test/test_robotparser.py`
- [ ] `test/test_sax.py`
- [ ] `test/test_scope.py`
- [ ] `test/test_script_helper.py`
- [ ] `test/test_select.py`
- [ ] `test/test_set.py`
  - See also #3992
- [ ] `test/test_setcomps.py`
- [ ] `test/test_slice.py`
- [ ] `test/test_smtpnet.py`
- [ ] `test/test_sort.py`
- [ ] `test/test_source_encoding.py`
- [ ] `test/test_spwd.py`
- [ ] `test/test_stable_abi_ctypes.py`
- [ ] `test/test_startfile.py`
- [ ] `test/test_strftime.py`
- [ ] `test/test_string.py`
- [ ] `test/test_string_literals.py`
- [ ] `test/test_strptime.py`
- [ ] `test/test_strtod.py`
- [ ] `test/test_structseq.py`
 -  See also #4063
- [ ] `test/test_subclassinit.py`
- [ ] `test/test_sundry.py`
- [ ] `test/test_super.py`
  - See also #3865
- [x] `test/test_support.py` #5078
  - [ ] #4538
- [ ] `test/test_syntax.py`
  - [ ] #4479
- [ ] `test.test_sys`
  - See also #3859
  - See also #4541
- [ ] `test/test_sys_setprofile.py`
- [ ] `test/test_sys_settrace.py`
- [ ] `test/test_syslog.py`
- [ ] `test/test_tcl.py`
- [ ] `test/test_thread.py`
- [ ] `test/test_threadedtempfile.py`
- [ ] `test/test_threadsignals.py`
- [ ] `test/test_time.py`
  - See also #3850
  - See also #4157
- [ ] `test/test_timeout.py`
- [ ] `test/test_tix.py`
- [ ] `test/test_tuple.py`
- [ ] `test/test_type_annotations.py`
- [ ] `test/test_type_cache.py`
- [ ] `test/test_type_comments.py`
- [ ] `test/test_typechecks.py`
- [ ] `test/test_types.py`
- [ ] `test/test_ucn.py`
- [ ] `test/test_unary.py`
- [x] `test/test_unicode.py` #5078
- [ ] `test/test_unicode_file.py`
- [ ] `test/test_unicode_file_functions.py`
- [ ] `test/test_unicode_identifiers.py`
- [ ] `test/test_unicodedata.py` 
- [ ] `test/test_univnewlines.py`
- [ ] `test/test_unpack.py` 
- [ ] `test/test_unpack_ex.py`
- [ ] `test/test_unparse.py`
- [ ] `test/test_userdict.py` 
- [ ] `test/test_userlist.py` 
- [ ] `test/test_userstring.py` 
- [ ] `test/test_utf8_mode.py`
- [ ] `test/test_utf8source.py`
- [ ] `test/test_wait3.py`
- [ ] `test/test_wait4.py`
- [ ] `test/test_weakset.py`
- [ ] `test/test_winconsoleio.py`
- [ ] `test/test_winreg.py`
- [ ] `test/test_winsound.py`
- [ ] `test/test_with.py`
- [ ] `test/test_yield_from.py`
- [x] `test/test_zlib.py` #5476
- [ ] `test/test_asyncio`
- [ ] `test/test_capi`
- [ ] `test/test_import`
- [ ] `test/test_tools`

# Not yet added libraries
These libraris are not added yet. Pure python one will be possible while others are not.

- [ ] `_bootsubprocess.py`
- [ ] `cProfile.py`
- [x] `crypt.py`  removed in 3.13
- [ ] `curses`
- [ ] `idlelib`
- [ ] `imaplib.py`
- [ ] `imp.py`
  - [ ] See also #4075
- [ ] `lzma.py`
- [x] `mailcap.py`  removed in 3.13
- [ ] `modulefinder.py`
  - [ ] #3846 
- [x] `msilib` removed in 3.13
- [x] `pipes.py`  removed in 3.13
- [ ] `poplib.py`
- [ ] `pstats.py`
- [ ] `pyclbr.py`
- [ ] `symtable.py`
- [ ] `tkinter`
- [ ] `tracemalloc.py`
- [ ] `turtle.py`
- [ ] `wave.py`
- [x] `zoneinfo` #5400

**Comment by Blues-star** [comment]
chunk.py doesn't need to be updated

**Comment by Eclips4** [comment]
`heap.py` doesn't need to be updated

**Comment by Eclips4** [comment]
`cgi.py` doesn't need to be updated
`test_cgi.py` also doesn't need to be updated

**Comment by jkauerl** [comment]
Hi, from this list, what is a good library and/or test to implement as a good first issue?

**Comment by youknowone** [comment]
@jkauerl Hi. In high chance, unpopular libraries are technically easy to update. But those are not that much fun. I'd like to encourage to try libraries you are already familiar with. Then understanding errors and bugs will be easier and enjoyable.

**Comment by arihant2math** [comment]
`test/test_zlib.py` has been updated to 3.12 as per #5476

**Comment by arihant2math** [comment]
`_compression.py` has either already been updated or has not changed. The same applies to `_markupbase.py`

**Comment by arihant2math** [comment]
Also the same for ` test/test_int_literal.py`

**Comment by hbina** [comment]
Doesn't look like test_binop.py changed.

**Comment by arihant2math** [comment]
This should probably be re-targeted to 3.1.3

**Comment by youknowone** [comment]
Thanks to everyone who participated in the 3.12 library support marathon for a year!
Based on this marathon, we are moving forward with Python 3.13 support in #5529
