### ISSUE TITLE
Tracking pip support in RustPython

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#5332]
Yes, we are almost there. But still many issues are scattered on multiple projects outside of RustPython.
This issue is tracking the status of related issues. 

- [ ] windows platformdirs requires ctypes #2671 
  - [x] patch in platformdirs: https://github.com/platformdirs/platformdirs/pull/275
  - [x] patch in pip: https://github.com/pypa/pip/pull/12670
  - [ ] New pip release

**Comment by cs50victor** [comment]
hey @youknowone, thanks for your work on this project. I'm interested in using rustpython in an open source project i'm working on. would closing this issue allow projects using rustpython as a crate be able to dynamically execute python files with import statements just like a jupyter notebook? how do i help with this?

**Comment by youknowone** [comment]
@cs50victor  Hi, RustPython already can import a lot of pure python packages while it is compatible to RustPython.
This issue is about installing a new package using `pip` command. This is *not* related to import step.

To help this issue, checking if the new release of those project included the patched code would be helpful. Once all of them are solved, I will update it and test them again.

**Comment by youknowone** [comment]
Libraries are all patched and released.

But recent pip is broken in RustPython #5584

**Comment by youknowone** [comment]
Okay, we fixed macos and linux PIP, but not yet windows.
Actually we never had working PIP on windows yet.
I submitted [another patch](https://github.com/tox-dev/platformdirs/pull/403) to platformdirs, which I had to also test when I wrote the first patch 🥲

**Comment by youknowone** [comment]
#6211 finally enabled PIP on windows

**Comment by vytas7** [comment]
I opened #7956 separately, feel free to move if it fits better as a bullet point here.
